name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          game-launcher-app/package-lock.json
    
    - name: Install root dependencies
      run: npm ci
      
    - name: Install app dependencies
      run: |
        cd game-launcher-app
        npm ci
        
    - name: Build app
      run: |
        cd game-launcher-app
        npm run build
        
    - name: Build Electron app
      run: |
        cd game-launcher-app
        npm run package
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: game-launcher-${{ github.sha }}
        path: game-launcher-app/release/*.exe
        
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          game-launcher-app/package-lock.json
    
    - name: Install dependencies
      run: |
        npm ci
        cd game-launcher-app
        npm ci
        
    - name: Build and publish
      run: |
        cd game-launcher-app
        npm run build
        npm run package
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 